# Generated by Django 3.0.11 on 2021-03-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-publish',)},
        ),
    ]
